config/routes.rb
Rails.application.routes.draw do    
  resources :return_notifications
  resources :libraries
  devise_for :users
  
  get 'books/notify', to: 'return_notifications#notify'
  get 'books/end_notify', to: 'return_notifications#end_notify'
  get 'books/borrow', to: 'checkout_logs#borrow'
  get 'books/return', to: 'checkout_logs#return'
  get 'books/my_books'
  get 'books/listing'
  get 'books/listing/:book_number' => 'books#details', :as => :book_listing_details
  get 'books/:id/add_copy' => 'books#add_copy', :as => :add_copy

  
  resources :books do    
    resources :checkout_logs
  end 

  get 'home/index'

  root to: "home#index"

  #match all other routes to 'url_not_found'
  match "*path", to: "application#url_not_found", via: :all  
end

app/models/checkout_log.rb
class CheckoutLog < ApplicationRecord
  belongs_to :user
  belongs_to :book

  #records per page for will_paginate
  self.per_page = 50
end

app/controllers/checkout_logs_controller.rb
class CheckoutLogsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin, except: [:borrow, :return]
  before_action :get_book, except: [:borrow, :return]
  before_action :set_checkout_log, only: [:show, :edit, :update, :destroy]

  # GET /checkout_logs
  # GET /checkout_logs.json
  def index
    @checkout_logs = @book.checkout_logs.paginate(page: params[:page]).order(:checkout_date)
  end

  # GET /checkout_logs/1
  # GET /checkout_logs/1.json
  def show    
  end

  # GET /checkout_logs/new
  def new
    @checkout_log = @book.checkout_logs.build
  end

  # GET /checkout_logs/1/edit
  def edit
  end

  #borrow book, create new checkout_log with duedate in 1 week
  #refactor create code  
  def borrow
    #take one book that matches book_number and doesn't have a checkout_log record with a null returned_date (ie an available book of book_number)
    @book = Book.where(book_number: params[:book_number], library_id: params[:library_id]).where.not(id: CheckoutLog.where(returned_date: nil).pluck(:book_id)).take 
    
    if @book
      @checkout_log = CheckoutLog.new(:checkout_date => Time.now,
                                    :due_date => Time.now + 1.week,
                                    :returned_date => :null,
                                    :user_id => current_user.id,
                                    :book_id => @book.id)
    else
      redirect_to books_listing_path, notice: 'None of those Books are currently available.' and return   
    end

    respond_to do |format|
      if @checkout_log.save
        format.html { redirect_to books_listing_path, notice: 'Book was successfully borrowed.' }
        format.json { render :show, status: :created, location: @checkout_log }
      else
        format.html { render :new }
        format.json { render json: @checkout_log.errors, status: :unprocessable_entity }
      end
    end    
  end

  #return book, update checkout_log returned_date to current time.  
  def return
    @checkout_log = CheckoutLog.find(params[:checkout_log_id])
    #verify correct user is trying to return this book 
    if @checkout_log.user_id == current_user.id
      #send out all return notifications      
      @book = Book.where(id: @checkout_log.book_id).take      
      @return_notifications = ReturnNotification.where(book_number: @book.book_number, library_id: @book.library_id)
      @return_notifications.find_each do |notification|
        user = User.where(:id => notification.user_id).take        
        @book = Book.where(:book_number => notification.book_number, :library_id => notification.library_id).take        
        ReturnNotificationMailer.with(user: user, book: @book).return_notifications.deliver_now

        #delete notification after e-mail sent. could later change table to flag as sent instead of deleting record
        notification.destroy
      end

      respond_to do |format|
        if @checkout_log.update(:returned_date => Time.now)
          format.html { redirect_to books_my_books_path, notice: 'Book was successfully returned.' }
          format.json { render :show, status: :ok, location: @checkout_log }
        else
          format.html { render :edit }
          format.json { render json: @checkout_log.errors, status: :unprocessable_entity }
        end
      end
    else
      #wrong user trying to return someone elses book
      redirect_to root_path
    end
  end


  # POST /checkout_logs
  # POST /checkout_logs.json
  def create
    @checkout_log = CheckoutLog.new(checkout_log_params)

    respond_to do |format|
      if @checkout_log.save
        format.html { redirect_to book_checkout_logs_path(@book), notice: 'Checkout log was successfully created.' }
        format.json { render :show, status: :created, location: @checkout_log }
      else
        format.html { render :new }
        format.json { render json: @checkout_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkout_logs/1
  # PATCH/PUT /checkout_logs/1.json
  def update
    respond_to do |format|
      if @checkout_log.update(checkout_log_params)
        format.html { redirect_to book_checkout_logs_path(@book), notice: 'Checkout log was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkout_log }
      else
        format.html { render :edit }
        format.json { render json: @checkout_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkout_logs/1
  # DELETE /checkout_logs/1.json
  def destroy
    @checkout_log.destroy
    respond_to do |format|
      format.html { redirect_to book_checkout_logs_path(@book), notice: 'Checkout log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private    
    #get book associated with this checkout_log
    def get_book
        @book = Book.find(params[:book_id])           
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_checkout_log
      @checkout_log = @book.checkout_logs.find(params[:id])      
    end

    # Only allow a list of trusted parameters through.
    def checkout_log_params
      params.require(:checkout_log).permit(:checkout_date, :due_date, :returned_date, :user_id, :book_id)
    end
end

app/helpers/checkout_logs_helper.rb
module CheckoutLogsHelper
end

app/views/checkout_logs/_form.html.erb
<%= form_with(model: [@book, @checkout_log], local: true) do |form| %>
  <% if checkout_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(checkout_log.errors.count, "error") %> prohibited this checkout_log from being saved:</h2>

      <ul>
        <% checkout_log.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="row">
    <dt class="col-sm-1"><%= form.label :checkout_date %></dt>
    <dd class="col-sm-11"> <%= form.datetime_select :checkout_date %></dd>

    <dt class="col-sm-1"> <%= form.label :due_date %></dt>
    <dd class="col-sm-11"><%= form.datetime_select :due_date %></dd>

    <dt class="col-sm-1"><%= form.label :returned_date %></dt>
    <dd class="col-sm-11"><%= form.datetime_select :returned_date %></dd>

    <dt class="col-sm-1"><%= form.label :subgenre %> </dt>
    <dd class="col-sm-11"> <%= form.text_field :subgenre %></dd>

    <dt class="col-sm-1"><%= form.label :user_id %></dt>
    <dd class="col-sm-11"><%= form.text_field :user_id %></dd>

    <dt class="col-sm-1"><%= form.label :book_id %></dt>
    <dd class="col-sm-11"><%= form.text_field :book_id %></dd> 
</dl>

  <div class="actions">
    <%= form.submit button_text, class: 'btn btn-primary py-0 m-1 btn-sm' %>
  </div>
<% end %>

app/views/checkout_logs/edit.html.erb
<h1>Editing Checkout Log</h1>

<%= render 'form', checkout_log: @checkout_log %>

<%= link_to 'Show', @checkout_log_path, class: 'btn btn-primary py-0 m-1 btn-sm' %> 
<%= link_to 'Back', book_checkout_logs_path(@book), class: 'btn btn-primary py-0 m-1 btn-sm' %>

app/views/checkout_logs/index.html.erb
<h1>Checkout Logs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Checkout Date</th>
      <th>Due Date</th>
      <th>Returned Date</th>      
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkout_logs.each do |checkout_log| %>
      <tr>
        <td><%= checkout_log.user_id %></td>
        <td><%= checkout_log.book_id %></td>
        <td><%= checkout_log.checkout_date&.strftime("%B %d, %Y, %l:%M%p") %></td>
        <td><%= checkout_log.due_date&.strftime("%B %d, %Y, %l:%M%p") %></td>
        <td><%= checkout_log.returned_date&.strftime("%B %d, %Y, %l:%M%p") %></td>
        <td>
          <%= link_to 'Show', book_checkout_log_path(@book, checkout_log), class: 'btn btn-primary py-0 btn-sm' %>
          <%= link_to 'Edit', edit_book_checkout_log_path(@book, checkout_log), class: 'btn btn-primary py-0 btn-sm' %>
          <%= link_to 'Destroy', book_checkout_log_path(@book, checkout_log), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary py-0 btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkout Log', new_book_checkout_log_path, class: 'btn btn-primary py-0 m-1 btn-sm' %>

<%= link_to 'Back', books_path, class: 'btn btn-primary py-0 m-1 btn-sm' %>

<%= will_paginate(@checkout_logs) %>

app/views/checkout_logs/new.html.erb
<h1>New Checkout Log</h1>

<%= render 'form', checkout_log: @checkout_log %>

<%= link_to 'Back', book_checkout_logs_path , class: 'btn btn-primary py-0 m-1 btn-sm' %>

app/views/checkout_logs/show.html.erb
<p>
  <strong>Checkout Date:</strong>
  <%= @checkout_log.checkout_date&.strftime("%B %d, %Y, %l:%M%p") %>
</p>

<p>
  <strong>Due Date:</strong>
  <%= @checkout_log.due_date&.strftime("%B %d, %Y, %l:%M%p") %>
</p>

<p>
  <strong>Returned Date:</strong>
  <%= @checkout_log.returned_date&.strftime("%B %d, %Y, %l:%M%p") %>
</p>

<p>
  <strong>User:</strong>
  <%= @checkout_log.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @checkout_log.book_id %>
</p>

<%= link_to 'Edit', edit_book_checkout_log_path(@checkout_log), class: 'btn btn-primary py-0 m-1 btn-sm' %>
<%= link_to 'Back', book_checkout_logs_path, class: 'btn btn-primary py-0 m-1 btn-sm' %>