config/routes.rb
Rails.application.routes.draw do    
  resources :return_notifications
  resources :libraries
  devise_for :users
  
  get 'books/notify', to: 'return_notifications#notify'
  get 'books/end_notify', to: 'return_notifications#end_notify'
  get 'books/borrow', to: 'checkout_logs#borrow'
  get 'books/return', to: 'checkout_logs#return'
  get 'books/my_books'
  get 'books/listing'
  get 'books/listing/:book_number' => 'books#details', :as => :book_listing_details
  get 'books/:id/add_copy' => 'books#add_copy', :as => :add_copy

  
  resources :books do    
    resources :checkout_logs
  end 

  get 'home/index'

  root to: "home#index"

  #match all other routes to 'url_not_found'
  match "*path", to: "application#url_not_found", via: :all  
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">

  <a class="navbar-brand text-white" href="/">City Library</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Book Listing', books_listing_path, class: 'nav-link text-white' %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Books', books_my_books_path, :user => current_user, class: 'nav-link text-white' %>
      </li>
      <% if current_user.try(:admin?) %> 
      <li class="nav-item dropdown">
        <a class="btn nav-link dropdown-toggle text-white" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Admin
        </a>
        <div class="dropdown-menu bg-primary" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Books', books_path, class: 'nav-link text-white dropdown-item' %>
          <%= link_to 'Libraries', libraries_path, class: 'nav-link text-white dropdown-item' %>
          <%= link_to 'Return Notifications', return_notifications_path, class: 'nav-link text-white dropdown-item' %>          
        </div>
      </li>
      <% end %>
      <% if user_signed_in? %>                       
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
      </li>        
      <% else %>
      <li class="nav-item">
        <%= link_to 'Register', new_user_registration_path, class: 'nav-link text-white' %>
      </li> 
      <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: 'nav-link text-white' %>
      </li> 
      <% end %>

       
    </ul>
    </div>
 
</nav>