config/routes.rb
Rails.application.routes.draw do    
  resources :return_notifications
  resources :libraries
  devise_for :users
  
  get 'books/notify', to: 'return_notifications#notify'
  get 'books/end_notify', to: 'return_notifications#end_notify'
  get 'books/borrow', to: 'checkout_logs#borrow'
  get 'books/return', to: 'checkout_logs#return'
  get 'books/my_books'
  get 'books/listing'
  get 'books/listing/:book_number' => 'books#details', :as => :book_listing_details
  get 'books/:id/add_copy' => 'books#add_copy', :as => :add_copy

  
  resources :books do    
    resources :checkout_logs
  end 

  get 'home/index'

  root to: "home#index"

  #match all other routes to 'url_not_found'
  match "*path", to: "application#url_not_found", via: :all  
end

app/models/return_notification.rb
class ReturnNotification < ApplicationRecord
  belongs_to :user
  belongs_to :library
  #belongs_to :book_number, :foreign_key => 'book_number', :class_name => 'Book', :primary_key => 'book_number'
end

app/controllers/return_notifications_controller.rb
class ReturnNotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin, except: [:notify, :end_notify]
  before_action :set_return_notification, only: %w[ show edit update destroy ]
  before_action :set_libraries, only: [:new,:edit]

  # GET /return_notifications
  # GET /return_notifications.json
  def index
    @return_notifications = ReturnNotification.all
  end

  # GET /return_notifications/1
  # GET /return_notifications/1.json
  def show
  end

  # GET /return_notifications/new
  def new
    @return_notification = ReturnNotification.new
  end

  # GET /return_notifications/1/edit
  def edit    
  end

  # POST /return_notifications
  # POST /return_notifications.json
  def create
    @return_notification = ReturnNotification.new(return_notification_params)

    respond_to do |format|
      if @return_notification.save
        format.html { redirect_to @return_notification, notice: "Return notification was successfully created." }
        format.json { render :show, status: :created, location: @return_notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @return_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /return_notifications
  # POST /return_notifications.json
  def notify
    @return_notification = ReturnNotification.new(:user_id => current_user.id,
                                                  :book_number => params[:book_number],
                                                  :library_id => params[:library_id])

    respond_to do |format|
      if @return_notification.save
        format.html { redirect_to books_listing_path, notice: "Return notification was successfully created." }
        format.json { render :show, status: :created, location: @return_notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @return_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /return_notifications/1
  # PATCH/PUT /return_notifications/1.json
  def update
    respond_to do |format|
      if @return_notification.update(return_notification_params)
        format.html { redirect_to @return_notification, notice: "Return notification was successfully updated." }
        format.json { render :show, status: :ok, location: @return_notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @return_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /return_notifications/1
  # DELETE /return_notifications/1.json
  def destroy
    @return_notification.destroy
    respond_to do |format|
      format.html { redirect_to return_notifications_url, notice: "Return notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def end_notify
    @return_notification = ReturnNotification.where(:user_id => current_user.id,
                                                    :book_number => params[:book_number],
                                                    :library_id => params[:library_id]).take
    @return_notification.destroy
    respond_to do |format|
      format.html { redirect_to books_listing_path, notice: "Return notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_libraries
      @libraries = Library.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_return_notification
      @return_notification = ReturnNotification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def return_notification_params
      params.require(:return_notification).permit(:user_id, :book_number, :library_id)
    end
end

app/helpers/return_notifications_helper.rb
module ReturnNotificationsHelper
end

app/views/return_notifications/_form.html.erb
<%= form_with(model: return_notification, local: true) do |form| %>
  <% if return_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(return_notification.errors.count, "error") %> prohibited this return_notification from being saved:</h2>

      <ul>
        <% return_notification.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<dl class="row">
  <dt class="col-sm-1"><%= form.label :user_id %></dt>
  <dd class="col-sm-11"><%= form.text_field :user_id %></dd>

  <dt class="col-sm-1"><%= form.label :book_number %></dt>
  <dd class="col-sm-11"><%= form.number_field :book_number %></dd>

  <dt class="col-sm-1"><%= form.label :library_id %></dt>
  <dd class="col-sm-11"><%= form.select :library_id, @libraries.collect { |library| [library.name, library.id]} %></dd> 
</dl>

<div class="actions">
  <%= form.button button_text, class: 'btn btn-primary py-0 m-1 btn-sm'%>
</div>

<% end %>

app/views/return_notifications/edit.html.erb
<h1>Editing Return Notification</h1>

<%= render 'form', return_notification: @return_notification %>

<%= link_to 'Show', @return_notification, class: 'btn btn-primary py-0 m-1 btn-sm' %>
<%= link_to 'Back', return_notifications_path, class: 'btn btn-primary py-0 m-1 btn-sm' %>

app/views/return_notifications/index.html.erb
<h1>Return Notifications</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Book number</th>
      <th>Library</th>
      <th>Created Date</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @return_notifications.each do |return_notification| %>
      <tr>
        <td><%= return_notification.user_id %></td>
        <td><%= return_notification.book_number %></td>
        <td><%= return_notification.library.name %></td>
        <td><%= return_notification.created_at&.strftime("%B %d, %Y, %l:%M%p") %></td>
        <td>
          <%= link_to 'Show', return_notification, class: 'btn btn-primary py-0 btn-sm' %>
          <%= link_to 'Edit', edit_return_notification_path(return_notification), class: 'btn btn-primary py-0 btn-sm' %>
          <%= link_to 'Destroy', return_notification, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger py-0 btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Return Notification', new_return_notification_path, class: 'btn btn-primary py-0 m-1 btn-sm' %>

app/views/return_notifications/new.html.erb
<h1>New Return Notification</h1>

<%= render 'form', return_notification: @return_notification %>

<%= link_to 'Back', return_notifications_path, class: 'btn btn-primary py-0 btn-sm' %>

app/views/return_notifications/show.html.erb
<p>
  <strong>User:</strong>
  <%= @return_notification.user_id %>
</p>

<p>
  <strong>Book number:</strong>
  <%= @return_notification.book_number %>
</p>

<p>
  <strong>Library:</strong>
  <%= @return_notification.library.name %>
</p>

<p>
  <strong>Created Date:</strong>
  <%= @return_notification.created_at&.strftime("%B %d, %Y, %l:%M%p") %>
</p>

<%= link_to 'Edit', edit_return_notification_path(@return_notification), class: 'btn btn-primary py-0 btn-sm' %>
<%= link_to 'Back', return_notifications_path, class: 'btn btn-primary py-0 btn-sm' %>