config/routes.rb
Rails.application.routes.draw do    
  resources :return_notifications
  resources :libraries
  devise_for :users
  
  get 'books/notify', to: 'return_notifications#notify'
  get 'books/end_notify', to: 'return_notifications#end_notify'
  get 'books/borrow', to: 'checkout_logs#borrow'
  get 'books/return', to: 'checkout_logs#return'
  get 'books/my_books'
  get 'books/listing'
  get 'books/listing/:book_number' => 'books#details', :as => :book_listing_details
  get 'books/:id/add_copy' => 'books#add_copy', :as => :add_copy

  
  resources :books do    
    resources :checkout_logs
  end 

  get 'home/index'

  root to: "home#index"

  #match all other routes to 'url_not_found'
  match "*path", to: "application#url_not_found", via: :all  
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :checkout_logs, dependent: :destroy
    belongs_to :library

    #records per page for will_paginate
    self.per_page = 100
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:listing]
  before_action :is_admin, except: [:listing, :my_books]
  before_action :set_book, only: [:show, :edit, :update, :destroy, :add_copy]
  before_action :set_libraries, only: [:new, :edit]

  # GET /books
  # GET /books.json
  def index    
    @books = Book.paginate(page: params[:page]).order(:title, :library_id)
  end

  # a list of all unique books
  # GET /books/listing
  def listing
    #TODO: find cleaner way to build this
    if current_user&.id
      user_id = current_user.id
    else
      user_id = 0
    end

    sql = "select
    title,
    author,
    genre,
    subgenre,
    pages,
    publisher,
    book.book_number,    
    count(book.book_number) as copies,
    count(log.book_id) as borrowed_copies,
    lib.name,
    book.library_id,
    notify.library_id,
    notify.book_number
    from books as book
    
    left join (
    select distinct
    book_id
    from checkout_logs
    where returned_date is null
    ) as log
    ON book.id = log.book_id

    left join (select * from libraries) lib
    ON lib.id = book.library_id

    left join (select * from return_notifications where user_id = #{ActiveRecord::Base.sanitize_sql(user_id)} ) notify
    ON 
    notify.book_number = book.book_number AND notify.library_id = lib.id
	
    group by 1,2,3,4,5,6,7,10,11,12,13
    ORDER BY book.title"
    @books = ActiveRecord::Base.connection.execute(sql).values
  end

  def details
    #TODO: find cleaner way to build this    
    @book = Book.where(book_number: params[:book_number], library_id: params[:library_id]).take  
    sql = "SELECT DISTINCT ON (books.id)
    books.id, users.email, c.returned_date, c.due_date
    FROM checkout_logs c
    RIGHT JOIN books
    ON c.book_id = books.id
    LEFT JOIN users
    on c.user_id = users.id
    where books.book_number = #{ActiveRecord::Base.sanitize_sql(params[:book_number])} and books.library_id = #{ActiveRecord::Base.sanitize_sql(params[:library_id])}
    ORDER BY books.id, c.returned_date DESC
    " 

    @checkout_logs = ActiveRecord::Base.connection.execute(sql).values
  end

  #list books for current user that are borrowed
  def my_books    
    @checkout_logs = CheckoutLog.joins(:book).where(checkout_logs: {user_id: current_user.id, returned_date: nil})  
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @checkout_logs = CheckoutLog.joins(:book).where(checkout_logs: {book_id: @book.id})
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create    
    @next_book_number = Book.maximum(:book_number).to_i.next
    #initially assign the next available book_number to this book
    @book = Book.new(book_params.merge!(:book_number => @next_book_number))
    @existing_identical_book = Book.where(title: @book.title,
                                          author: @book.author,
                                          genre: @book.genre,
                                          subgenre: @book.subgenre,
                                          pages: @book.pages,
                                          publisher: @book.publisher).take
    #if an existing identical book exists, then make the book_number match before saving the new book to database
    if @existing_identical_book
      @book.book_number = @existing_identical_book.book_number  
    end                                        

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  #add another copy of an existing book
  def add_copy    
    @book_new_copy = @book.dup                       

    respond_to do |format|
      if @book_new_copy.save
        format.html { redirect_to @book_new_copy, notice: 'Copy was successfully created.' }
        format.json { render :show, status: :created, location: @book_new_copy }
      else
        format.html { render :new }
        format.json { render json: @book_new_copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json  
  def update    
    @existing_identical_book = Book.where(title: book_params[:title],
                                          author: book_params[:author],
                                          genre: book_params[:genre],
                                          subgenre: book_params[:subgenre],
                                          pages: book_params[:pages],
                                          publisher: book_params[:publisher]
                                        ).take
    #if an existing identical book exists, then make the book_number match otherwise set to a new book_number
    if @existing_identical_book
      params[:book_number] = @existing_identical_book.book_number  
    else
      params[:book_number] = Book.maximum(:book_number).to_i.next
    end

    respond_to do |format|
      if @book.update(book_params.merge!(:book_number => params[:book_number]))
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_libraries
      @libraries = Library.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :genre, :subgenre, :pages, :publisher,:book_number, :library_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<dl class="row">
  <dt class="col-sm-1"><%= form.label :title %> </dt>
  <dd class="col-sm-11"><%= form.text_field :title %></dd>

  <dt class="col-sm-1"><%= form.label :author %> </dt>
  <dd class="col-sm-11"><%= form.text_field :author %></dd>

  <dt class="col-sm-1"><%= form.label :genre %> </dt>
  <dd class="col-sm-11"><%= form.text_field :genre %></dd>

  <dt class="col-sm-1"><%= form.label :subgenre %> </dt>
  <dd class="col-sm-11"> <%= form.text_field :subgenre %></dd>

  <dt class="col-sm-1"> <%= form.label :pages %></dt>
  <dd class="col-sm-11"><%= form.number_field :pages %></dd>

  <dt class="col-sm-1"><%= form.label :publisher %></dt>
  <dd class="col-sm-11"><%= form.text_field :publisher %></dd>

  <dt class="col-sm-1"><%= form.label :library_id %></dt>
  <dd class="col-sm-11"><%= form.select :library_id, @libraries.collect { |library| [library.name, library.id]} %></dd> 
</dl>

  <div class="actions">
    <%= form.button button_text, class: 'btn btn-primary py-0 m-1 btn-sm'%>
  </div>
<% end %>

app/views/books/details.html.erb
<h1>Book Details</h1>

<p>
  <strong>Book Number:</strong>
  <%= @book.book_number %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Subgenre:</strong>
  <%= @book.subgenre %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @book.pages %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Library:</strong>
  <%= @book.library.name %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>BookId</th>      
      <th>Status</th>          
    </tr>
  </thead>

  <tbody>
    <% @checkout_logs.each do |checkout_log| %>
      <tr>
        <td><%= checkout_log[0] %></td>        
        <td><%= (!checkout_log[2] && checkout_log[3]? "Signed out by " + checkout_log[1] : "Available") %></td>             
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book, class: 'btn btn-primary py-0 m-1 btn-sm' %>
<%= link_to 'Back', books_path, class: 'btn btn-primary py-0 m-1 btn-sm' %>

app/views/books/index.html.erb
<div class="row">
  <div class="col-11">
    <h1>Books</h1>
  </div>
  <div class="col-1 align-self-end">
    <% if current_user.try(:admin?) %>   
    <%= link_to 'New Book', new_book_path , class: 'btn btn-primary py-0 btn-sm'%>
    <% end %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Subgenre</th>
      <th>Pages</th>
      <th>Publisher</th>
      <th>Library</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.subgenre %></td>
        <td><%= book.pages %></td>
        <td><%= book.publisher %></td>
        <td><%= book.library.name %></td>            
        <% if current_user.try(:admin?) %>
        <td>
          <%= link_to 'Show', book_path(book), class: 'btn btn-primary py-0 btn-sm' %>
          <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-primary py-0 btn-sm' %>
          <%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm py-0' %>
          <%= link_to 'Add Copy', add_copy_path(book), class: 'btn btn-primary py-0 btn-sm' %>
          <%= link_to 'Checkout Logs', book_checkout_logs_path(book), class: 'btn btn-primary py-0 btn-sm' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">    
    <%= will_paginate @books, :container => false %>
</div>

app/views/books/listing.html.erb
<h1>Book Listing</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Subgenre</th>
      <th>Pages</th>
      <th>Publisher</th>
      <th>Library</th>
      <th>Total Copies</th>
      <th>Available Copies</th>      
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book[0] %></td>
        <td><%= book[1] %></td>
        <td><%= book[2] %></td>
        <td><%= book[3] %></td>
        <td><%= book[4] %></td>
        <td><%= book[5] %></td>
        <td><%= book[9] %></td>
        <td><%= book[7] %></td>
        <td><%= book[7] - (book[8]? book[8] : 0) %></td>
        <td>
        <% if current_user.try(:admin?) %>
        <%= link_to 'Details',  book_listing_details_path(:book_number => book[6], :library_id =>book[10]) , class: 'btn btn-primary py-0 m-1 btn-sm' %>
        <% end %>
        <% if current_user && book[7] - (book[8]? book[8] : 0) > 0 %>           
        <%= link_to 'Borrow',  books_borrow_path(:book_number => book[6], :library_id =>book[10]) , class: 'btn btn-primary py-0 m-1 btn-sm' %>
        <% else %>
        <%    if current_user && (!book[12] && !book[13]) %>
        <%= link_to 'Notify on Return', books_notify_path(:book_number => book[6], :library_id => book[10]), class: 'btn btn-secondary py-0 m-1 btn-sm' %>
        <%    elsif current_user %>
        Return Notification <%= link_to 'x', books_end_notify_path(:book_number => book[6], :library_id => book[10]), class: 'btn btn-danger py-0 btn-sm' %>
        <%    end %>
        <% end %>  
        </td>      
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/my_books.html.erb
<h1>My Books</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Subgenre</th>
      <th>Pages</th>
      <th>Publisher</th>
      <th>Library</th>
      <th>Due Date</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkout_logs.each do |checkout_log| %>
      <tr>
        <td><%= checkout_log.book.id %></td>
        <td><%= checkout_log.book.title %></td>
        <td><%= checkout_log.book.author %></td>
        <td><%= checkout_log.book.genre %></td>
        <td><%= checkout_log.book.subgenre %></td>
        <td><%= checkout_log.book.pages %></td>
        <td><%= checkout_log.book.publisher %></td>
        <td><%= checkout_log.book.library.name %></td>
        <td><%= checkout_log.due_date&.strftime("%B %d, %Y, %l:%M%p") %></td>
        <td><%= link_to 'Return', books_return_path(:checkout_log_id => checkout_log.id), class: 'btn btn-primary py-0 m-1 btn-sm' %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path , class: 'btn btn-primary py-0 m-1 btn-sm'%>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Subgenre:</strong>
  <%= @book.subgenre %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @book.pages %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Library:</strong>
  <%= @book.library.name %>
</p>
<% if current_user.try(:admin?) %>
<%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-primary py-0 m-1 btn-sm' %>
<% end %>
<%= link_to 'Back', books_path, class: 'btn btn-primary py-0 m-1 btn-sm' %>

<% if current_user.try(:admin?) %>
<br>
<br>
<h4> Checkout History </h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>      
      <th>Checkout Date</th>
      <th>Due Date</th>
      <th>Returned Date</th>            
    </tr>
  </thead>

  <tbody>
    <% @checkout_logs.each do |checkout_log| %>    
      <tr>
        <td><%= checkout_log.user.email %></td>        
        <td><%= checkout_log.checkout_date&.strftime("%B %d, %Y, %l:%M%p") %></td>
        <td><%= checkout_log.due_date&.strftime("%B %d, %Y, %l:%M%p") %></td>
        <td><%= checkout_log.returned_date&.strftime("%B %d, %Y, %l:%M%p") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>